version: '3.8'

services:

  spad1-frontend-control-panel:
    image: us-central1-docker.pkg.dev/score-416214/spad-platform/spad1-frontend-control-panel:latest
    container_name: spad1-frontend-home
    build:
        context: .
        dockerfile: ./Dockerfile
    ports:
      - '4200:80'
    restart: unless-stopped
